<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'MigrateStore\\Exporters\\AbstractExporter' => $baseDir . '/includes/Exporters/AbstractExporter.php',
    'MigrateStore\\Exporters\\WooCommerce\\AccountsPrivacyExporter' => $baseDir . '/includes/Exporters/WooCommerce/AccountsPrivacyExporter.php',
    'MigrateStore\\Exporters\\WooCommerce\\EmailsOptionsExporter' => $baseDir . '/includes/Exporters/WooCommerce/EmailsOptionsExporter.php',
    'MigrateStore\\Exporters\\WooCommerce\\EndpointsExporter' => $baseDir . '/includes/Exporters/WooCommerce/EndpointsExporter.php',
    'MigrateStore\\Exporters\\WooCommerce\\GeneralSettingsExporter' => $baseDir . '/includes/Exporters/WooCommerce/GeneralSettingsExporter.php',
    'MigrateStore\\Exporters\\WooCommerce\\ShippingOptionsExporter' => $baseDir . '/includes/Exporters/WooCommerce/ShippingOptionsExporter.php',
    'MigrateStore\\Exporters\\WooCommerce\\ShippingZonesExporter' => $baseDir . '/includes/Exporters/WooCommerce/ShippingZonesExporter.php',
    'MigrateStore\\Exporters\\WooCommerce\\TaxOptionsExporter' => $baseDir . '/includes/Exporters/WooCommerce/TaxOptionsExporter.php',
    'MigrateStore\\Importers\\AbstractImporter' => $baseDir . '/includes/Importers/AbstractImporter.php',
    'MigrateStore\\Importers\\WooCommerce\\AccountsPrivacyImporter' => $baseDir . '/includes/Importers/WooCommerce/AccountsPrivacyImporter.php',
    'MigrateStore\\Importers\\WooCommerce\\EmailsOptionsImporter' => $baseDir . '/includes/Importers/WooCommerce/EmailsOptionsImporter.php',
    'MigrateStore\\Importers\\WooCommerce\\EndpointsImporter' => $baseDir . '/includes/Importers/WooCommerce/EndpointsImporter.php',
    'MigrateStore\\Importers\\WooCommerce\\GeneralSettingsImporter' => $baseDir . '/includes/Importers/WooCommerce/GeneralSettingsImporter.php',
    'MigrateStore\\Importers\\WooCommerce\\ShippingOptionsImporter' => $baseDir . '/includes/Importers/WooCommerce/ShippingOptionsImporter.php',
    'MigrateStore\\Importers\\WooCommerce\\ShippingZonesImporter' => $baseDir . '/includes/Importers/WooCommerce/ShippingZonesImporter.php',
    'MigrateStore\\Importers\\WooCommerce\\TaxOptionsImporter' => $baseDir . '/includes/Importers/WooCommerce/TaxOptionsImporter.php',
    'MigrateStore\\MigrateStore' => $baseDir . '/includes/MigrateStore.php',
    'MigrateStore\\Plugins_Checker' => $baseDir . '/includes/Plugins_Checker.php',
);
