<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5575b02ee58333e1ce3d1fc76a1fcf09
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MigrateWoo\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MigrateWoo\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5575b02ee58333e1ce3d1fc76a1fcf09::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5575b02ee58333e1ce3d1fc76a1fcf09::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit5575b02ee58333e1ce3d1fc76a1fcf09::$classMap;

        }, null, ClassLoader::class);
    }
}
